# Site settings.
title: TheProduct.Space
description: The product space is a playbook of product management techniques and best practises for product development teams
baseurl: # the subpath of your site, e.g. /blog
url: "https://theproduct.space"

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Enable or disable the site search
search_enabled: true

# Use just the docs theme
theme: just-the-docs

# Aux links for the upper right navigation
aux_links:
  "About":
    - "/about"
  "Contribute":
    - "//github.com/mrkrumhausen/product-space"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking
ga_tracking: UA-10127534-3
